name: "Build iOS app"

# on: [push]
on: [workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: build archive and ipaify
        run: |
          wget -O archive.zip "https://www.dropbox.com/scl/fi/8uvch6yf7un7z9k17myly/bbc243a2-5076-11f1-af8f-2089843c3c33.zip?rlkey=5fujl8e9ziklti88av7081rl9&dl=1"
          unzip archive.zip -d .

          xcodebuild archive -project RB4v6.xcodeproj -scheme 'RB4v6' -archivePath RB4v6.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

          mkdir Payload
          mv RB4v6.xcarchive/Products/Applications/RB4v6.app Payload/RB4v6.app

          zip -r "RB4v6.ipa" "Payload"

          mv RB4v6.ipa ${{ runner.temp }}/RB4v6.ipa


      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: RB4v6
          path: ${{ runner.temp }}/RB4v6.ipa
          # you can also archive the entire directory
          # path: ${{ runner.temp }}/build
          retention-days: 3