name: "Build iOS app"

# on: [push]
on: [workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: build archive and ipaify
        run: |
          wget -O archive.zip "https://www.dropbox.com/scl/fi/ebirxifm3ee0rdch12a0n/8eacbdde-af7c-11f1-9327-2089843c3c33.zip?rlkey=h4j907716jnsn8yqom3u5010g&dl=1"
          unzip archive.zip -d .

          xcodebuild archive -project EFIV.xcodeproj -scheme 'EFIV' -archivePath EFIV.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

          mkdir Payload
          mv EFIV.xcarchive/Products/Applications/EFIV.app Payload/EFIV.app

          zip -r "EFIV.ipa" "Payload"

          mv EFIV.ipa ${{ runner.temp }}/EFIV.ipa


      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: EFIV
          path: ${{ runner.temp }}/EFIV.ipa
          # you can also archive the entire directory
          # path: ${{ runner.temp }}/build
          retention-days: 3